### ISSUE TITLE
retain order

### ISSUE THREAD

**Issue by quake** [triplehex/hashlink#10]
the retain fn visiting each element in an undetermined order, is it possible to change it to inserting order, make this unit test pass?
```rust
fn test_retain_order() {
    let xs = [1, 2, 3, 4, 5, 6];
    let mut set: LinkedHashSet<i32> = xs.iter().cloned().collect();
    let mut vec = Vec::new();
    set.retain(|&k| {
        if k % 2 == 0 {
            true
        } else {
            vec.push(k);
            false
        }
    });
    assert_eq!(vec![1, 3, 5], vec);
}
```

**Comment by kyren** [comment]
I also commented on PR #11, but I'm not entirely sure what the right behavior is, given the extra trait bounds and performance implications of implementing ordered retain.  I'd feel more comfortable with a separate ordered method than changing the current one, but I'm unsure if that's even that beneficial.
